<a href="https://colab.research.google.com/github/scysco/ONE-DATASCIENCE/blob/main/06_Pandas_transformaci%C3%B3n_manipulaci%C3%B3n_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROBLEMA DE NEGOCIO


---

Se trata de un algoritmo capaz de nalizar las caracteristica de una propiedad(como comodidades, tama√±o, ocupacion del espacio en un perido determinado) y sugerir al anfitrion un precio a cobrar por tarifas diarias que garantice ganancias en momentos de alta demanda.

## 1. Entendiendo el Problema

In [1]:
import pandas as pd
datos = pd.read_json('/content/drive/MyDrive/ONE/06_Pandas_DATA/datos_hosting.json')
datos.head()

                                      info_inmuebles
0  {'evaluacion_general': '10.0', 'experiencia_lo...
1  {'evaluacion_general': '10.0', 'experiencia_lo...
2  {'evaluacion_general': '10.0', 'experiencia_lo...
3  {'evaluacion_general': '10.0', 'experiencia_lo...
4  {'evaluacion_general': '10.0', 'experiencia_lo...

Normalizo datos:

In [2]:
datos = pd.json_normalize(datos['info_inmuebles'])
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_ba√±os,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

## 2. Datos numericos

In [3]:
columnas = list(datos.columns)
columnas

['evaluacion_general',
 'experiencia_local',
 'max_hospedes',
 'descripcion_local',
 'descripcion_vecindad',
 'cantidad_ba√±os',
 'cantidad_cuartos',
 'cantidad_camas',
 'modelo_cama',
 'comodidades',
 'cuota_deposito',
 'cuota_limpieza',
 'precio']

**Aplico explode despues de 'descripcion_local'**

In [4]:
datos = datos.explode(columnas[3:])
datos

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_ba√±os,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The ‚ÄúStudio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

**Reconstruyo inidices**

In [5]:
datos.reset_index(inplace=True, drop=True)
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_ba√±os,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The ‚ÄúStudio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

**Convierto datos numericos**

In [6]:
import numpy as np
datos['max_hospedes'] = datos['max_hospedes'].astype(np.int64)
datos['max_hospedes']

0       1
1       1
2       1
3       1
4       1
       ..
3813    8
3814    8
3815    8
3816    9
3817    9
Name: max_hospedes, Length: 3818, dtype: int64

Optmizando proceso

In [7]:
col_numericas = ['cantidad_ba√±os', 'cantidad_cuartos', 'cantidad_camas']
datos[col_numericas]= datos[col_numericas].astype(np.int64)

In [8]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_ba√±os        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

Flotantes

In [9]:
datos['evaluacion_general'] = datos['evaluacion_general'].astype(np.float64)

Limpiando datos

In [10]:
datos['precio'] = datos['precio'].apply(lambda x: x.replace('$','').replace(',','').strip())

In [11]:
datos['precio'] = datos['precio'].astype(np.float64)

In [12]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_ba√±os        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

Optimizando proceso con map

In [13]:
datos[['cuota_deposito','cuota_limpieza']] = datos[['cuota_deposito','cuota_limpieza']].map(lambda x: x.replace('$','').replace(',','').strip())

In [14]:
datos[['cuota_deposito','cuota_limpieza']]  = datos[['cuota_deposito','cuota_limpieza']].astype(np.float64)

In [15]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_ba√±os        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   float64
 11  cuota_limpieza        3818 non-null   float64
 12  precio                3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

## 3. Datos de Texto

Pasamos a minusculas

In [16]:
datos['descripcion_local'].str.lower()

0       this clean and comfortable one bedroom sits ri...
1       our century old upper queen anne house is loca...
2       cozy room in two-bedroom apartment along the l...
3       very lovely and cozy room for one. convenientl...
4       the ‚Äústudio at mibbett hollow' is in a beautif...
                              ...
3813    beautiful craftsman home in the historic wedgw...
3814    located in a very easily accessible area of se...
3815    this home is fully furnished and available wee...
3816    this business-themed modern home features:  *h...
3817    this welcoming home is in the quiet residentia...
Name: descripcion_local, Length: 3818, dtype: object

Elimino caracteres especiales "descripcion_local"

In [17]:
datos['descripcion_local'] = datos['descripcion_local'].str.replace('[^a-zA-Z0-9\-\']',' ', regex=True)

In [18]:
datos['descripcion_local'] = datos['descripcion_local'].str.replace('(?<!\w)-(?!\w)',' ', regex=True)

In [19]:
datos['descripcion_local'].head()

0    This clean and comfortable one bedroom sits ri...
1    Our century old Upper Queen Anne house is loca...
2    Cozy room in two-bedroom apartment along the l...
3    Very lovely and cozy room for one  Convenientl...
4    The  Studio at Mibbett Hollow' is in a Beautif...
Name: descripcion_local, dtype: object

Tokenizacion "descripcion_local"

In [20]:
datos['descripcion_local'] = datos['descripcion_local'].str.split()
datos['descripcion_local']

0       [This, clean, and, comfortable, one, bedroom, ...
1       [Our, century, old, Upper, Queen, Anne, house,...
2       [Cozy, room, in, two-bedroom, apartment, along...
3       [Very, lovely, and, cozy, room, for, one, Conv...
4       [The, Studio, at, Mibbett, Hollow', is, in, a,...
                              ...
3813    [Beautiful, craftsman, home, in, the, historic...
3814    [Located, in, a, very, easily, accessible, are...
3815    [This, home, is, fully, furnished, and, availa...
3816    [This, business-themed, modern, home, features...
3817    [This, welcoming, home, is, in, the, quiet, re...
Name: descripcion_local, Length: 3818, dtype: object

Tratamiendo de 'comodidades'

In [21]:
datos['comodidades'] = datos['comodidades'].str.replace('\{|\}|\"','',regex=True)

In [22]:
datos['comodidades'] = datos['comodidades'].str.split(',')
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_ba√±os,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,"[This, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[Our, century, old, Upper, Queen, Anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.0
2,10.0,--,1,"[Cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.0
3,10.0,--,1,"[Very, lovely, and, cozy, room, for, one, Conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[The, Studio, at, Mibbett, Hollow', is, in, a,...",--,1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.0

Tratamiento de 'descripcion_vecindad'

In [23]:
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.lower()
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.replace('(?<!\w)-(?!\w)', '', regex=True)
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.split()
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_ba√±os,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,"[This, clean, and, comfortable, one, bedroom, ...","[lower, queen, anne, is, near, the, seattle, c...",1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[Our, century, old, Upper, Queen, Anne, house,...","[upper, queen, anne, is, a, really, pleasant, ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.0
2,10.0,--,1,"[Cozy, room, in, two-bedroom, apartment, along...","[the, convenience, of, being, in, seattle, but...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.0
3,10.0,--,1,"[Very, lovely, and, cozy, room, for, one, Conv...","[ballard, is, lovely, vibrant, and, one, of, t...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[The, Studio, at, Mibbett, Hollow', is, in, a,...",[],1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.0

## 4. Datos de tiempo

In [24]:
dt_data = pd.read_json('/content/drive/MyDrive/ONE/06_Pandas_DATA/inmuebles_disponibles.json')
dt_data.head()

    id       fecha  lugar_disponible precio
0  857  2016-01-04             False   None
1  857  2016-01-05             False   None
2  857  2016-01-06             False   None
3  857  2016-01-07             False   None
4  857  2016-01-08             False   None

In [25]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  object
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

Tratamiento de 'fecha'

In [26]:
dt_data['fecha'] = pd.to_datetime(dt_data['fecha'])
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  datetime64[ns]
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [27]:
dt_data.head()

    id      fecha  lugar_disponible precio
0  857 2016-01-04             False   None
1  857 2016-01-05             False   None
2  857 2016-01-06             False   None
3  857 2016-01-07             False   None
4  857 2016-01-08             False   None

Cuantos inmubles disponibles por mes

In [28]:
dt_data['fecha'].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: fecha, Length: 365000, dtype: object

In [29]:
subset = dt_data.groupby(dt_data['fecha'].dt.strftime('%Y-%m'))['lugar_disponible'].sum()
subset

fecha
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: lugar_disponible, dtype: int64

Transformando precio a tipo float

In [30]:
dt_data['precio'].fillna('0.0', inplace = True)
dt_data['precio'] = dt_data['precio'].apply(lambda x: x.replace('$', '').replace(',',''))
dt_data['precio'] = dt_data['precio'].astype(np.float64)
dt_data

/tmp/ipython-input-4198033597.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt_data['precio'].fillna('0.0', inplace = True)

          id      fecha  lugar_disponible  precio
0        857 2016-01-04             False     0.0
1        857 2016-01-05             False     0.0
2        857 2016-01-06             False     0.0
3        857 2016-01-07             False     0.0
4        857 2016-01-08             False     0.0
...      ...        ...               ...     ...
364995  3279 2016-12-29              True   140.0
364996  3279 2016-12-30              True   140.0
364997  3279 2016-12-31              True   140.0
364998  3279 2017-01-01              True   140.0
364999  3279 2017-01-02             False     0.0

[365000 rows x 4 columns]

# Proyecto Desaf√≠o 1: Ventas Online


---

El objetivo de este proyecto es analizar los resultados de un evento con los clientes de una empresa de venta online. Se recopil√≥ un conjunto de datos que contiene los clientes que m√°s gastaron en productos durante los 5 d√≠as de ventas, que es la duraci√≥n del evento. Este an√°lisis identificar√° al cliente con la mayor compra esta semana, quien recibir√° un premio de la tienda, y posteriormente, puede ayudar a la empresa a crear nuevas estrategias para atraer m√°s clientes.

La base de datos utilizada en este an√°lisis es dados_vendas_clientes.json y contiene informaci√≥n importante sobre los clientes, como el nombre registrado del cliente, el monto total pagado al momento de la compra y el d√≠a de la compra.

Sabiendo esta informaci√≥n, el desaf√≠o del proyecto 1: ventas online ser√° abrir la base de datos con Pandas y aplicar json_normalize.

In [31]:
import pandas as pd
data_ventas = pd.read_json('/content/drive/MyDrive/ONE/06_Pandas_DATA/dados_vendas_clientes.json')
data_ventas = pd.json_normalize(data_ventas['dados_vendas'])
data_ventas.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JO√£O Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

**Desafio:**
* Eliminar datos en listas dentro del DataFrame;
* Verificar tipos de datos;
* Identificar columnas num√©ricas;
* Transformar la columna num√©rica a tipo num√©rico.

In [32]:
data_ventas_columns = list(data_ventas.columns)
data_ventas_columns

['Data de venda', 'Cliente', 'Valor da compra']

In [33]:
data_ventas = data_ventas.explode(data_ventas_columns[1:])
data_ventas.reset_index(drop=True,inplace=True) # reconstruyo index
data_ventas

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JO√£O Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

Convierto "Valor da compra" a tipo float

In [34]:
import numpy as np
data_ventas['Valor da compra'] = data_ventas['Valor da compra'].apply(lambda x: x.replace('R$ ', '').replace(',','.').strip())
data_ventas['Valor da compra'] = data_ventas['Valor da compra'].astype(np.float64)

data_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

Debido a una inestabilidad en el sitio web de la empresa, tuvimos problemas con los nombres de los clientes durante el guardado. Esto result√≥ en una columna de nombres de clientes con una combinaci√≥n de letras, may√∫sculas y min√∫sculas, n√∫meros y otros caracteres.

Sabiendo esto, manipula los textos de la columna Cliente para que el resultado sean los nombres de los clientes en letras min√∫sculas, con ausencia de caracteres especiales o n√∫meros.

In [35]:
data_ventas['Cliente'] = data_ventas['Cliente'].str.lower()
data_ventas.head()
data_ventas['Cliente'].str.replace('[^a-z ]', '', regex=True)
data_ventas['Cliente'] = data_ventas['Cliente'].str.replace('[^a-z ]', '', regex=True).str.strip()
data_ventas.head()

  Data de venda         Cliente  Valor da compra
0    06/06/2022       ana lucia           836.50
1    06/06/2022  diego armandiu           573.33
2    06/06/2022  diego armandiu           392.80
3    06/06/2022  diego armandiu           512.34
4    07/06/2022  isabely joanes           825.31

En la columna Fecha de venta tenemos fechas en el formato 'd√≠a/mes/a√±o' (dd/mm/AAAA). Transforme estos datos al tipo datetime y busque una forma de visualizaci√≥n de subconjunto que pueda contribuir al objetivo del contexto en el que se insertan los datos.

In [44]:
data_ventas['Data de venda'] = pd.to_datetime(data_ventas['Data de venda'], format='%d/%m/%Y')
data_ventas

   Data de venda         Cliente  Valor da compra
0     2022-06-06       ana lucia           836.50
1     2022-06-06  diego armandiu           573.33
2     2022-06-06  diego armandiu           392.80
3     2022-06-06  diego armandiu           512.34
4     2022-06-07  isabely joanes           825.31
5     2022-06-07  isabely joanes           168.07
6     2022-06-07  isabely joanes           339.18
7     2022-06-07  isabely joanes           314.69
8     2022-06-08  isabely joanes           682.05
9     2022-06-08     joo gabriel           386.34
10    2022-06-08  julya meireles           622.65
11    2022-06-08  julya meireles           630.79
12    2022-06-09  julya meireles           390.30
13    2022-06-09     maria julia           759.16
14    2022-06-09     maria julia           334.47
15    2022-06-09     maria julia           678.78
16    2022-06-10     maria julia           314.24
17    2022-06-10     pedro pasco           311.15
18    2022-06-10    paulo castro           899.16
19    2022-06-10   thiago fritzz           885.24

In [45]:
data_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [46]:
total_compras = data_ventas.groupby(['Cliente'])['Valor da compra'].sum()

In [47]:
total_compras

Cliente
ana lucia          836.50
diego armandiu    1478.47
isabely joanes    2329.30
joo gabriel        386.34
julya meireles    1643.74
maria julia       2086.65
paulo castro       899.16
pedro pasco        311.15
thiago fritzz      885.24
Name: Valor da compra, dtype: float64

# Proyecto Desaf√≠o 2: Administraci√≥n de Condominios


---

Administrar condominios es una tarea que requiere mucha atenci√≥n y organizaci√≥n. Entre las diversas responsabilidades de gesti√≥n se encuentra el cobro del alquiler a los inquilinos. Para garantizar la buena salud financiera de la empresa, es fundamental que estos pagos se realicen de forma regular y puntual. Sin embargo, sabemos que esto no siempre sucede.

Teniendo esto en cuenta, propongo un desaf√≠o de procesamiento de datos con el objetivo de analizar el retraso en el pago del alquiler en el condominio de algunos residentes. Pongo a disposici√≥n la base de datos dados_locacao_imoveis.json, que contiene informaci√≥n sobre el departamento de los inquilinos, el d√≠a acordado para el pago del alquiler, el d√≠a en que se realiza el pago del alquiler y el monto del alquiler.

Con esta informaci√≥n, el desaf√≠o del proyecto 2: administraci√≥n del condominio ser√° similar al desaf√≠o del proyecto 1, abrir la base de datos con Pandas y aplicar json_normalize al DataFrame.

In [36]:
import pandas as pd
data_condominios = pd.read_json('/content/drive/MyDrive/ONE/06_Pandas_DATA/dados_locacao_imoveis.json')
data_condominios = pd.json_normalize(data_condominios['dados_locacao'])
data_condominios.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

**Desafio:**
* Eliminar datos en listas dentro del DataFrame;
* Verificar tipos de datos;
* Identificar columnas num√©ricas;
* Transformar la columna num√©rica a tipo num√©rico.

In [37]:
data_condominios_columns = list(data_condominios.columns)
data_condominios_columns

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [38]:
data_condominios = data_condominios.explode(data_condominios_columns[1:])
data_condominios.reset_index(drop=True,inplace=True)
data_condominios

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [39]:
data_condominios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

Convierto valores de 'valor_aluguel' a tipo float

In [40]:
import numpy as np
data_condominios['valor_aluguel'] = data_condominios['valor_aluguel'].apply(lambda x: x.replace('$ ', '').replace(' reais', '').replace(',','.').strip())
data_condominios['valor_aluguel'] = data_condominios['valor_aluguel'].astype(np.float64)
data_condominios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

Buscando explicar la organizaci√≥n de la identificaci√≥n de los apartamentos, durante la creaci√≥n del conjunto de datos se a√±adi√≥ el texto (blocoAP). Este texto informa que los nombres de los apartamentos est√°n organizados con la letra may√∫scula seguida del n√∫mero del apartamento. Sin embargo, esto no aporta ninguna informaci√≥n a nuestros datos, por lo que resulta interesante eliminar este texto del conjunto de datos.

Con esto, manipule los textos de la columna apartamento para eliminar el texto (blocoAP) del DataFrame.

In [41]:
data_condominios['apartamento'].str.replace(' \(blocoAP\)', '')
data_condominios['apartamento'] = data_condominios['apartamento'].str.replace(' \(blocoAP\)', '')
data_condominios

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
1,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
2,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
3,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
4,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
5,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
6,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
7,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
8,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
9,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
10,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
11,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
12,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
13,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
14,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
15,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
16,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
17,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
18,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
19,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
20,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
21,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
22,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
23,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
24,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
25,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
26,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
27,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
28,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
29,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

En las columnas datas_de_pagamento y datas_combinadas_pagamento tenemos fechas en el formato 'd√≠a/mes/a√±o' (dd/mm/AAAA). Transforme estos datos al tipo datetime y busque una forma de visualizaci√≥n de subconjunto que pueda contribuir al objetivo del contexto en el que se insertan los datos.

In [48]:
data_condominios['datas_combinadas_pagamento'] = pd.to_datetime(data_condominios['datas_combinadas_pagamento'], format='%d/%m/%Y')
data_condominios['datas_de_pagamento'] = pd.to_datetime(data_condominios['datas_de_pagamento'], format='%d/%m/%Y')
data_condominios

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),2022-06-01,2022-06-05,1000.0
1,A101 (blocoAP),2022-07-01,2022-07-03,2500.0
2,A102 (blocoAP),2022-06-02,2022-06-02,1100.0
3,A102 (blocoAP),2022-07-02,2022-07-06,2600.0
4,B201 (blocoAP),2022-06-03,2022-06-07,1200.0
5,B201 (blocoAP),2022-07-03,2022-07-03,2700.0
6,B202 (blocoAP),2022-06-04,2022-06-07,1300.0
7,B202 (blocoAP),2022-07-04,2022-07-05,2800.0
8,C301 (blocoAP),2022-06-05,2022-06-10,1400.0
9,C301 (blocoAP),2022-07-05,2022-07-09,2900.0
10,C302 (blocoAP),2022-06-06,2022-06-08,1500.0
11,C302 (blocoAP),2022-07-06,2022-07-12,1200.0
12,D401 (blocoAP),2022-06-07,2022-06-07,1600.0
13,D401 (blocoAP),2022-07-07,2022-07-09,1300.0
14,D402 (blocoAP),2022-06-08,2022-06-10,1700.0
15,D402 (blocoAP),2022-07-08,2022-07-14,1400.0
16,E501 (blocoAP),2022-06-09,2022-06-10,1800.0
17,E501 (blocoAP),2022-07-09,2022-07-09,1500.0
18,E502 (blocoAP),2022-06-10,2022-06-16,1900.0
19,E502 (blocoAP),2022-07-10,2022-07-12,1600.0
20,F601 (blocoAP),2022-06-11,2022-06-17,2000.0
21,F601 (blocoAP),2022-07-11,2022-07-13,1000.0
22,F602 (blocoAP),2022-06-12,2022-06-15,2100.0
23,F602 (blocoAP),2022-07-12,2022-07-12,1100.0
24,G701 (blocoAP),2022-06-13,2022-06-19,2200.0
25,G701 (blocoAP),2022-07-13,2022-07-20,1200.0
26,G702 (blocoAP),2022-06-14,2022-06-15,2300.0
27,G702 (blocoAP),2022-07-14,2022-07-17,2100.0
28,H801 (blocoAP),2022-06-15,2022-06-18,2400.0
29,H801 (blocoAP),2022-07-15,2022-07-16,2200.0

In [49]:
data_condominios['atraso'] = (data_condominios['datas_de_pagamento'] - data_condominios['datas_combinadas_pagamento']).dt.days
data_condominios

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101 (blocoAP),2022-06-01,2022-06-05,1000.0,4
1,A101 (blocoAP),2022-07-01,2022-07-03,2500.0,2
2,A102 (blocoAP),2022-06-02,2022-06-02,1100.0,0
3,A102 (blocoAP),2022-07-02,2022-07-06,2600.0,4
4,B201 (blocoAP),2022-06-03,2022-06-07,1200.0,4
5,B201 (blocoAP),2022-07-03,2022-07-03,2700.0,0
6,B202 (blocoAP),2022-06-04,2022-06-07,1300.0,3
7,B202 (blocoAP),2022-07-04,2022-07-05,2800.0,1
8,C301 (blocoAP),2022-06-05,2022-06-10,1400.0,5
9,C301 (blocoAP),2022-07-05,2022-07-09,2900.0,4
10,C302 (blocoAP),2022-06-06,2022-06-08,1500.0,2
11,C302 (blocoAP),2022-07-06,2022-07-12,1200.0,6
12,D401 (blocoAP),2022-06-07,2022-06-07,1600.0,0
13,D401 (blocoAP),2022-07-07,2022-07-09,1300.0,2
14,D402 (blocoAP),2022-06-08,2022-06-10,1700.0,2
15,D402 (blocoAP),2022-07-08,2022-07-14,1400.0,6
16,E501 (blocoAP),2022-06-09,2022-06-10,1800.0,1
17,E501 (blocoAP),2022-07-09,2022-07-09,1500.0,0
18,E502 (blocoAP),2022-06-10,2022-06-16,1900.0,6
19,E502 (blocoAP),2022-07-10,2022-07-12,1600.0,2
20,F601 (blocoAP),2022-06-11,2022-06-17,2000.0,6
21,F601 (blocoAP),2022-07-11,2022-07-13,1000.0,2
22,F602 (blocoAP),2022-06-12,2022-06-15,2100.0,3
23,F602 (blocoAP),2022-07-12,2022-07-12,1100.0,0
24,G701 (blocoAP),2022-06-13,2022-06-19,2200.0,6
25,G701 (blocoAP),2022-07-13,2022-07-20,1200.0,7
26,G702 (blocoAP),2022-06-14,2022-06-15,2300.0,1
27,G702 (blocoAP),2022-07-14,2022-07-17,2100.0,3
28,H801 (blocoAP),2022-06-15,2022-06-18,2400.0,3
29,H801 (blocoAP),2022-07-15,2022-07-16,2200.0,1

In [50]:
media_atraso = data_condominios.groupby(['apartamento'])['atraso'].mean()
media_atraso

apartamento
A101 (blocoAP)    3.0
A102 (blocoAP)    2.0
B201 (blocoAP)    2.0
B202 (blocoAP)    2.0
C301 (blocoAP)    4.5
C302 (blocoAP)    4.0
D401 (blocoAP)    1.0
D402 (blocoAP)    4.0
E501 (blocoAP)    0.5
E502 (blocoAP)    4.0
F601 (blocoAP)    4.0
F602 (blocoAP)    1.5
G701 (blocoAP)    6.5
G702 (blocoAP)    2.0
H801 (blocoAP)    2.0
Name: atraso, dtype: float64